name: Print Line on Pull Request

on:
  pull_request:
    branches:
      - main  # Specify the branch you want to trigger this action for

jobs:
  print-line:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print a line
        run: echo "A pull request has been made!"
